0xMiden/compiler

Cargo.lock, Cargo.toml, ir/Cargo.toml, ir/src/hir/block.rs, ir/src/hir/builder.rs, ir/src/hir/dataflow.rs, ir/src/hir/function.rs, ir/src/hir/immediates.rs, ir/src/hir/instruction.rs, ir/src/hir/layout.rs, ir/src/hir/mod.rs, ir/src/hir/value.rs, ir/src/lib.rs, ir/src/types.rs
The stage 1 IR (or HIR), is a sea-of-nodes style, SSA form intermediate representation. It is intended to be a target from higher level languages, so it supports a wider array of operations and control flow than is supported in MASM (and in the stage 2 IR), but provides a useful foundation on which to perform the necessary analyses and transformations in order to lower to MASM.
This commit introduces the basic infrastructure for the IR, namely the minimum data structures necessary to represent functions in the IR, which are composed of blocks containing one or more instructions in a specific order. The set of instructions defined is based on what is provided in MASM, as well as what is needed to represent programs written in Sway or Move (barring some features which we can not yet support …
=> feat: implement stage 1 (hir) infra

ir/src/hir/builder.rs
builder.rs now builds Pow2 operations as UnaryOps rather than as BinaryOps.
=> Build Pow2 opcode as unary op rather than binary op

tools/midenc/src/compiler/emitter.rs, tools/midenc/src/compiler/mod.rs, tools/midenc/src/compiler/options.rs
I'm struggling to figure out how the emitter is supposed to fit in with the other stuff in the `midenc` directory and with `miden-diagnostics`. This draft PR is my current attempt, but I have no idea if it's anywhere close to what we need, and what the exact division of responsibilities is supposed to be between the various files.
For instance, the `Emitter` trait doesn't seem to use file names at all, so presumably the file buffer we need to write to is passed to the emitter from the outside?
=> MASM code emitter

Cargo.toml, hir/src/constants.rs, hir/src/globals.rs, hir/src/lib.rs, hir/src/module.rs, hir/src/program.rs, hir/src/segments.rs
Wasm has the concept of "data segments", essentially initializers for specific regions of memory, identified by offset from the start of linear memory, and a vector of bytes to be written starting at that offset. This is used to implement things like the `rodata` section you'd find in a typical ELF executable/library. Globals can then be exported with an address pointing into that segment, which can be useful for sharing the same data across many read-only globals, and for packing global data more efficiently.
Our implementation of this is very similar, except we also allow data segments to have a size larger than the initializer (byte vector), which has the same semantics as padding the initializer with zeroes out to that size.
--
This PR also implements formatting for segments, as well …
=> feat: implement support for wasm data segments

Cargo.lock, Cargo.toml, codegen/masm/Cargo.toml, codegen/masm/src/tests.rs, hir-analysis/Cargo.toml, hir-analysis/src/lib.rs, hir-analysis/src/validation/block.rs, hir-analysis/src/validation/function.rs, hir-analysis/src/validation/mod.rs, hir-analysis/src/validation/naming.rs, hir-analysis/src/validation/typecheck.rs, hir-transform/Cargo.toml, hir-transform/src/treeify.rs, hir/Cargo.toml, hir/src/block.rs, hir/src/dataflow.rs, hir/src/function.rs, hir/src/immediates.rs, hir/src/lib.rs, hir/src/testing.rs, hir/src/tests.rs
This PR implements the following in the `hir-analysis` crate:
* The `Rule` trait, used to implement validation rules for different types of IR items
* The `ModuleValidator` pass, used to run a suite of validations against modules and the functions they contain
* A suite of validation rules for things critical areas where we want to catch errors in the IR before attempting to process it for code generation: naming conventions, function signatures, ensuring blocks are valid, and that key properties of the SSA representation are upheld, such as value uses being dominated by their definitions, as well as a type-checking rule.
A few other commits are present which add some trait implementations for some types, some test infrastructure, etc., but each are isolated into independent commits.
=> feat: implement validation pass and supporting infrastructure

Cargo.lock, Cargo.toml, codegen/masm/Cargo.toml, codegen/masm/src/masm/function.rs, codegen/masm/src/masm/module.rs, codegen/masm/src/masm/program.rs, hir/Cargo.toml, hir/src/asm/isa.rs
As the PR title states, this enables conversion from our internal MASM IR to the "real" MASM representation provided by the `miden-assembly` crate. We can then emit to disk using those APIs, compile via the assembler, or run with the Miden VM.
NOTE: This PR omits a couple things pending some other work:
1. Emission of MASL libraries is blocked by 0xPolygonMiden/miden-vm#1108
2. The initialization of root context memory (i.e. writing data segments to the heap) is not yet implemented. We'll probably implement something here in the near future, but I'm punting a bit while I work on some other things
3. The function table that we'll want to write to memory to support `dynexec` is on hold until #32 is implemented
=> feat: implement conversion of masm ir to 'real' masm

.github/workflows/ci.yml
Right now we're running both the `push` and `pull_request` workflows on every PR, which is redundant
=> ci: only run push workflow on push to main

Cargo.lock, frontend-wasm/Cargo.toml, frontend-wasm/tests/expected/dlmalloc.mir, frontend-wasm/tests/expected/dlmalloc.wat, frontend-wasm/tests/expected/signed_arith.mir, frontend-wasm/tests/expected/signed_arith.wat, frontend-wasm/tests/test_rust_comp.rs
Close #41    
The function names in both the .mir and .wat files are demangled in tests before `expect!` comparison. This makes tests stable when the Rust toolchain version changes and more readable.
=> Demangle function names in Rust compilation tests comparison

codegen/masm/src/stackify/emitter.rs
This closes #52, and ensures the same issue won't happen again by removing the (no longer necessary) assertion that triggered it in the first place.
=> fix: unreachable raises assertion during stackification

codegen/masm/src/emulator/mod.rs, codegen/masm/src/stackify/emitter.rs, hir/src/asm/builder.rs, hir/src/asm/display.rs, hir/src/asm/isa.rs
This implements support for storing elements/words to locals in the MASM instruction set, and cleans up the ISA code a bit. This was originally part of #39, but that PR is being closed, and I'm extracting these changes from that PR to be merged separately.
=> feat: support loc_store(w) instructions

frontend-wasm/src/ssa.rs, tests/integration/expected/fib.hir, tests/integration/expected/fib.masm, tests/integration/expected/fib.wat, tests/rust-apps/fib/src/lib.rs
Cherry-picked commit from #58 
Close #51
Close #40 since the only use case for `emit_zero` at the start of the block was in the code removed by this PR.
**This PR is ready for review but is built on top and is intended to be merged after #49.**
This removes the remnants of the previously removed `ValueData::Alias` variant. It does not matter if we find the definition in the predecessors since we cannot swap all sentinel value uses with it. So, this fix always makes the sentinel value into a block argument.
=> Always create the destination branch argument for the sentinel value when looking for the value definition in the predecessors

frontend-wasm/src/function_builder_ext.rs, hir-analysis/src/validation/block.rs, hir-transform/src/inline_blocks.rs, hir/src/block.rs, hir/src/builder.rs, hir/src/dataflow.rs, hir/src/layout.rs
This patches the inline-blocks pass to ensure that inlined blocks are not visited multiple times by the inliner - once inlined, these blocks are treated as not inlineable from that point forward, allowing us to visit successor blocks with the inliner normally without considering the inlined block itself.
Additionally, the following issues are addressed:
* We did not raise an error if attempting to remove a node from its OrderedArenaMap if it had already been removed. These nodes remain accessible via the map so that outstanding references are still usable, but are treated in all other respects as if they are not contained in the map - this was not being handled properly by `remove`
* The `link` field of `BlockData` was superfluous and has been for some time, but was missed because it is a …
=> fix: improper handling of inlined blocks in inline-blocks transform

docs/book.toml
This PR updates `mdbook` config. Without these changes, the docs get built in a different directory and the deploy job does not pick them up. We could also change the CI job to deploy from different directory, but I think being able to write formulas in docs is generally useful.
=> Fix mdbook config

.gitignore, Makefile.toml, bin/filecheck, bin/lit, tests/lit/parse/fib.hir, tests/lit/parse/lit.suite.toml
This commit simply wires up the test suite, follow on PRs will introduce the actual tests for the suite. Until that is done, test-lit has been removed from the default test command to avoid annoying developers until the suite is stable.
@greenhat I added an example test here for you to look at, but it currently is busted due to a parser issue. The suite is temporarily disabled while I get a few more tests written up and all of them passing, but this just makes sure the infra is in place.
=> feat: set up lit infrastructure

frontend-wasm/src/code_translator/mod.rs, frontend-wasm/src/code_translator/tests.rs
**This PR is stacked on top of #106**
This PR is a pre-requisite for PR #100 since `cabi_realloc` uses the `memory.copy` op.
This PR adds a translation for Wasm `memory.copy` op.
=> Translate Wasm `memory.copy` op 

frontend-wasm/src/component/build_ir.rs, frontend-wasm/src/component/translator.rs, frontend-wasm/src/config.rs, hir/src/component/mod.rs, tests/integration/expected/components/inc_wasm_component.hir, tests/integration/expected/sdk_basic_wallet/basic_wallet.hir, tests/integration/src/rust_masm_tests/components.rs, tests/integration/src/rust_masm_tests/sdk.rs
**This PR is stacked on top of #131 and should be merged after it**
Since at component boundaries, every function is invoked via `call`.
=> [3/x] Remove invocation method from component imports/exports

docs/src/guides/rust_to_wasm.md, docs/src/guides/wasm_to_masm.md
- Fixed small errors in the example shell code
- Modified example `lib.rs` to match test case (was throwing type error previously)
- Stripped whitespace in guide docs
=> docs: fix broken example code snippets

tests/integration/src/exec_emulator.rs, tests/integration/src/exec_vm.rs, tests/integration/src/rust_masm_tests/instructions.rs
This PR fixes semantic tests for Rust ops in the integration test suite. Before, tests were silently failing due to using `println!` instead of `panic!` in case of the `proptest` runner error. 
I've fixed all the failing tests besides some u32 bin ops, for which I made #174
=> [2.5/x] Fix Rust ops semantic tests (silently failing before)

codegen/masm/src/codegen/emit/mem.rs, codegen/masm/src/codegen/emitter.rs
Otherwise, the subsequent `store`/`load` will fail (expecting a `Ptr`).
=> [0/x] Fix: add `inttoptr` after emitting the address of a global variable

codegen/masm/src/codegen/scheduler.rs, codegen/masm/src/masm/function.rs, frontend-wasm/src/miden_abi/transform.rs, hir/src/pass/rewrite.rs
This PR applies some fixes that were causing the basic wallet account code from #186 to hit asserts in the backend. Once merged, the only remaining blockers are related to felts, stores of complex types, load/store reordering, and operand stack overflow handling.
=> fix: basic wallet account compilation

codegen/masm/intrinsics/mem.masm, codegen/masm/src/codegen/emit/mem.rs
@greenhat This PR implements the most likely needed operations for stores involving felts or machine-width integer values. I haven't yet implemented 64-bit integers and larger, or aggregate types, but I'm opening this now so you have something you can work with while those get implemented.
NOTE: I have not really tested these implementations, but they are based on the same principles as the `load` ops. Definitely need testing here, but again, mostly looking to get the ABI testing unblocked, if there are bugs here, we can sort those out as they come until we have time to do more thorough testing.
=> feat: implement stores for felts/machine-width values

Cargo.lock, Cargo.toml, tests/integration/Cargo.toml, tests/integration/src/rust_masm_tests/abi_transform/stdlib.rs
This PR adds a semantic test (Rust vs. VM) for calling stdlib blake3 2-to-1 hash function.
=> Semantic test for calling stdlib's blake3 hash function

Cargo.lock, Cargo.toml, hir/src/asm/builder.rs, hir/src/asm/isa.rs, tests/integration/src/compiler_test.rs
**This PR is stacked on the #210 and should be merged after it**
This PR updates Miden VM crates to include empty `if.true` support introduced in 
https://github.com/0xPolygonMiden/miden-vm/pull/1360
=> [8/x] Update the Miden VM deps  with  empty `if.true` support

tests/integration/src/cargo_proj/mod.rs, tests/integration/src/compiler_test.rs, tests/integration/src/rust_masm_tests/rust_sdk.rs
Close #213 
**This PR is stacked on the #217 and should be merged after it**
=> [10/x] Introduce `SKIP_RUST` env var to skip rust compilation in some integration tests

midenc-compile/src/stages/parse.rs
**This PR is stacked on the #218 and should be merged after it**
Use `FileName::as_str` for source name in Wasm translation to avoid `<name>` (enclosed in brackets) which is produced by `FileName::to_string` since the brackets are illegal in MASM module ids.
=> [11/x] Use`FileName::as_str`for source file name to avoid enclosing virtual filenames in brackets

Cargo.toml
This PR fixes slow diffs for long texts in the expect tests.
=> Build `expect-test` with release profile to speed up diffs

.github/workflows/release.yml, CONTRIBUTING.md, release-plz.toml
Close #216 
Close #142 
This PR adds the Miden SDK crates publishing in the`release.yml` GA workflow and updates CONTRIBUTING.md.
After this PR is merged, I'm going to make and publish the first release for the compiler and SDK crates using the instructions in CONTRIBUTING.md.
=> Add Miden SDK crates release workflow

tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.hir, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.masm, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.wat, tests/integration/src/compiler_test.rs, tests/integration/src/rust_masm_tests/abi_transform/tx_kernel.rs
Close #223 
**This PR is stacked on the #222 and should be merged after it**
=> [2/x] `CompilerTest` stubs generation for imported functions in MASM program

codegen/masm/src/emulator/mod.rs, tests/integration/src/compiler_test.rs, tests/integration/src/rust_masm_tests/abi_transform/stdlib.rs, tests/integration/src/rust_masm_tests/abi_transform/tx_kernel.rs, tests/integration/src/rust_masm_tests/apps.rs, tests/integration/src/rust_masm_tests/instructions.rs, tests/integration/src/rust_masm_tests/intrinsics.rs, tests/integration/src/rust_masm_tests/mod.rs
**This PR is stacked on the #226 and should be merged after it**
=> [4/x] Restore running MASM in the emulator along the VM in integration tests

tests/integration/src/exec_vm.rs, tests/integration/src/rust_masm_tests/abi_transform/tx_kernel.rs
**This PR is stacked on #232 and should be merged after it**
=> [6/x] Add traced execution option on the VM in the integration tests

codegen/masm/src/emulator/mod.rs
**This PR is stacked on the #233 and should be merged after it**
=> [7/x] Fix memory cleanup in `Emulator::stop`

codegen/masm/src/codegen/scheduler.rs, hir-analysis/src/dependency_graph.rs, hir/src/instruction.rs, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.masm
Our instruction scheduler is based on a block-local data dependency graph that is decomposed into a structure we call a treegraph. The topological ordering of nodes in the treegraph, determines the order in which expression trees in a block will be scheduled.
This necessarily led to the need for some notion of control dependencies: first to ensure that the block terminator was always the last thing scheduled; then to handle instructions with no results that had side effects, as our dead-code elimination pass would remove nodes from the dependency graph which appeared dead, and control dependencies ensured that they were both kept live, and scheduled late in the block.
One thing we didn't handle however, was implicit control dependencies, manifested in the relationship between instructions …
=> feat(codegen): teach instruction scheduler about side effects

codegen/masm/src/codegen/emit/mem.rs, codegen/masm/src/emulator/memory.rs, codegen/masm/src/emulator/mod.rs, codegen/masm/src/tests.rs, hir/src/asm/stack.rs
**This PR is stacked on the #236 and should be merged after it**
=> [8/x] Add `Emulator::print_trace` option to print the current stack and memory on every step

codegen/masm/intrinsics/mem.masm, codegen/masm/src/tests.rs
**This PR is stacked on the #237 and should be merged after it**
Close #234 
Close #230
This PR fixes the following errors:
- assert in `intrinsics::mem::replace_element`,
- storing not in the word address in `intrinsics::mem::store_felt_unchecked`,
- loading from not from a pointer, but a value(partial) in `intrinsics::mem::load_sw` causing "out of bounds memory access".
Adds proptest for `mem::intrinsics::store_sw/load_sw`.
=> [9/x] Test for `mem::intrinsics::store_sw/load_sw`, fix `assert` in `get_inputs` test (`clk=451`) and other errors

codegen/masm/src/codegen/emit/int32.rs, codegen/masm/src/codegen/emit/unary.rs, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.masm
for casting `i32 <-> u32` and `i32 -> u64`
Close #250
=> Use new `OpEmitter::assert_i32` instead of `assert_unsigned_int32`

Cargo.lock, Cargo.toml, hir-macros/Cargo.toml
This PR fixes the issues described at https://github.com/0xPolygonMiden/compiler/issues/246#issuecomment-2239215588
After merging this PR, the GA should try to publish all unpublished crates again (see the branch prefix).
=> chore: fix `categories` and add `version` to all deps in workspace Cargo.toml

release-plz.toml
Ref #246 
Disables the git tag creation when publishing crates.
=> Disable tag creation on release PR merging(`release` command)

tools/cargo-miden/src/new_project.rs, tools/cargo-miden/tests/build.rs
Close #165 
QoL improvements to the cargo extension new project template test: select the local path to the template in the test.
Switch `cargo miden new` command to use the template with git tag `v0.2.0` set after https://github.com/0xPolygonMiden/rust-templates/pull/4 (basic wallet example) was merged.
=> chore: switch new project template to basic wallet example and use git tag for it in cargo-miden

codegen/masm/src/masm/program.rs
This PR skips pretty printing for the `stdlib` and intrinsics modules to focus on user code and as a workaround for https://github.com/0xPolygonMiden/miden-formatting/issues/4
=> chore: skip pretty printing stdlib and intrinsics modules in MASM `Program`

.github/workflows/release.yml, CONTRIBUTING.md, Cargo.lock, Cargo.toml, hir-macros/CHANGELOG.md, hir-macros/Cargo.toml, midenc-debug/CHANGELOG.md, midenc-debug/Cargo.toml, midenc-session/CHANGELOG.md, midenc-session/Cargo.toml, sdk/base-sys/CHANGELOG.md, sdk/base-sys/Cargo.toml
Ref #246 
This PR when merged will trigger the CI job to publish all the unpublished crates to crates.io.
Also in this PR:
- switch release PRs to be branched from the `next` branch instead of `main`, i.e. merging a release PR to `next` will trigger the publishing process;
- add `miden-sdk` and `miden-stdlib-sys` crates to the workspace.
=> Release v0.0.1 (take 5): Initial release of the compiler and SDK crates

tools/cargo-miden/src/new_project.rs
Close #282 
PR in `rust-templates` - https://github.com/0xPolygonMiden/rust-templates/pull/5
=> chore: update cargo extension to use new project template v0.3.0 (our alloc)

.github/workflows/release.yml, CONTRIBUTING.md
This should fix `release-plz` CI job failing on every merge to the `next` branch.
=> [1/2] chore: remove separate SDK crates publishing on CI since they are now published as a part of the workspace

Cargo.toml
Fix `cargo release` by adding `help` feature to `clap` dependency, since `cargo build` seems to ignore `default-features` on the workspace level and enables default features for inherited dependencies. `cargo release` OTOH seems to behave correctly and does not ignore `default-features` on the workspace level, and the build fails due to `Command::help_template` is hidden behind the `help` feature.
This PR fixes the https://github.com/0xPolygonMiden/compiler/actions/runs/10604566214/job/29391504068 build error during the `cargo release`
=> Release v0.0.1 (take 8): Initial release of the compiler and SDK crates

Cargo.lock, Cargo.toml, codegen/masm/Cargo.toml, frontend-wasm/Cargo.toml, hir-analysis/Cargo.toml, hir-macros/Cargo.toml, hir-symbol/Cargo.toml, hir-transform/Cargo.toml, hir-type/Cargo.toml, hir/Cargo.toml, midenc-compile/Cargo.toml, midenc-debug/Cargo.toml, midenc-driver/Cargo.toml, midenc-session/Cargo.toml, midenc/Cargo.toml, sdk/alloc/Cargo.toml, sdk/base-sys/Cargo.toml, sdk/sdk/Cargo.toml, sdk/stdlib-sys/Cargo.toml, tests/rust-apps-wasm/rust-sdk/account-test/Cargo.lock, tools/cargo-miden/Cargo.toml
Ref #296 
This is a release PR (CI job will publish all unpublished crate versions).
This PR bumps all crate versions to `v0.0.4` as a fix to #296
=> Release v0.0.4 (take 2)

Cargo.lock, Cargo.toml, codegen/masm/Cargo.toml, frontend-wasm/Cargo.toml, hir-analysis/Cargo.toml, hir-macros/Cargo.toml, hir-symbol/Cargo.toml, hir-transform/Cargo.toml, hir-type/Cargo.toml, hir/Cargo.toml, midenc-compile/Cargo.toml, midenc-debug/Cargo.toml, midenc-driver/Cargo.toml, midenc-session/Cargo.toml, midenc/Cargo.toml, sdk/alloc/Cargo.toml, sdk/base-sys/Cargo.toml, sdk/sdk/Cargo.toml, sdk/stdlib-sys/Cargo.toml, tools/cargo-miden/Cargo.toml
This is a release PR (crates are published after the merge).
All the crate versions are bumped to `v0.0.5`
The #297 failed due to the not-bumped `midenc-session` which pulls and old `midenc-hir-symbol` dependency.
=> Release v0.0.5

Cargo.lock, Cargo.toml, codegen/masm/Cargo.toml, frontend-wasm/Cargo.toml, hir-analysis/Cargo.toml, hir-macros/Cargo.toml, hir-symbol/Cargo.toml, hir-transform/Cargo.toml, hir-type/Cargo.toml, hir/Cargo.toml, midenc-compile/Cargo.toml, midenc-debug/Cargo.toml, midenc-driver/Cargo.toml, midenc-session/Cargo.toml, midenc/Cargo.toml, sdk/alloc/Cargo.toml, sdk/base-sys/Cargo.toml, sdk/sdk/Cargo.toml, sdk/stdlib-sys/Cargo.toml, tools/cargo-miden/Cargo.toml
Ref #296 
This PR switches the member crates to use the single `workspace.package.version` instead of specifying a separate version for each member crate.
See the https://github.com/0xPolygonMiden/compiler/issues/296#issuecomment-2326343060 for details.
=> chore: switch all crates to a single workspace version (0.0.5)

Cargo.lock, Cargo.toml, codegen/masm/CHANGELOG.md, frontend-wasm/CHANGELOG.md, hir-analysis/CHANGELOG.md, hir-macros/CHANGELOG.md, hir-symbol/CHANGELOG.md, hir-transform/CHANGELOG.md, hir-type/CHANGELOG.md, hir/CHANGELOG.md, midenc-compile/CHANGELOG.md, midenc-debug/CHANGELOG.md, midenc-driver/CHANGELOG.md, midenc-session/CHANGELOG.md, midenc-session/Cargo.toml, midenc/CHANGELOG.md, sdk/alloc/CHANGELOG.md, sdk/base-sys/CHANGELOG.md, sdk/base-sys/Cargo.toml, sdk/sdk/CHANGELOG.md, sdk/sdk/Cargo.toml, sdk/stdlib-sys/CHANGELOG.md, tools/cargo-miden/CHANGELOG.md
Publish 0.0.6 to crates.io, with recent fixes to the initial 0.0.5 release. This is my first time running the release process myself, but so far so good, all that remains is for our release automation to do the rest.
@bobbinth Same deal as the last PR, if you have a moment and can sign off, that'd be great - but it's not a big deal. The updated docs depend on some things in this release, but as they haven't been published yet, we can certainly wait until @greenhat is online for this one
=> release: 0.0.6

tests/integration/src/compiler_test.rs
Needed when running `cargo flamegraph --root` for #317
=> chore: fallback to cwd if CARGO_MANIFEST_DIR env var is not set

Cargo.lock, Cargo.toml, tests/integration/Cargo.toml, tests/integration/src/compiler_test.rs, tools/cargo-miden/src/lib.rs
Close #312
The `CompilerInputTestType::CargoComponent` will be removed, and all relevant tests will be switched to the `CargoMiden` variant after the #90 and #308 are implemented.
=> chore: add `CompilerTestInputType::CargoMiden` and use `cargo-miden` build it

tools/cargo-miden/src/new_project.rs, tools/cargo-miden/tests/build.rs
Close #323 
rust-templates PR - https://github.com/0xPolygonMiden/rust-templates/pull/6
This PR also adds a test to build the new project with `dev` profile.
=> Switch cargo-miden to v0.4.0 of the new project template with `dev` profile to fix the #323 compilation issue

sdk/base-sys/Cargo.toml, sdk/base-sys/build.rs
Use `miden-assembly` dependency only when building MASL library.
=> chore: remove `miden-assembly` dependency from `sdk/base-sys` for `bindings` feature

dialects/hir/src/builders/function.rs, dialects/hir/src/lib.rs, dialects/hir/src/ops/binary.rs, frontend-wasm/src/module/func_translator.rs, frontend-wasm/src/module/function_builder_ext.rs, frontend-wasm/src/ssa.rs, frontend-wasm2/src/code_translator/mod.rs, frontend-wasm2/src/module/build_ir.rs, frontend-wasm2/src/module/func_translation_state.rs, frontend-wasm2/src/module/func_translator.rs, frontend-wasm2/src/module/function_builder_ext.rs, frontend-wasm2/src/ssa.rs, frontend-wasm2/src/translation_utils.rs, hir2/src/dialects/builtin/ops/function.rs, hir2/src/ir/context.rs, hir2/src/ir/print.rs, tests/integration/expected/fib_hir2.hir, tests/integration/expected/fib_hir2.wat, tests/integration/src/rust_masm_tests/apps.rs
Ref #363 
**This PR is based on the #367**
This PR implements `CondBr`, `Br` and `Loop` ops along with the missing parts in the `SSABuilder` to successfully translate `fib` test code (see `fib_hir2` test).
=> Implement CondBr, Br, Loop translations; add `fib` test  

dialects/hir/src/builders/function.rs, dialects/hir/src/ops/invoke.rs, frontend-wasm2/src/code_translator/mod.rs, frontend-wasm2/src/code_translator/tests.rs, frontend-wasm2/src/module/build_ir.rs, frontend-wasm2/src/module/instance.rs, frontend-wasm2/src/module/module_translation_state.rs, frontend-wasm2/src/translation_utils.rs, hir2/src/dialects/builtin/builders/module.rs, hir2/src/dialects/builtin/ops/function.rs, hir2/src/ir/symbols/table.rs, tests/integration/expected/function_call_hir2.hir, tests/integration/expected/function_call_hir2.wat, tests/integration/src/cargo_proj/mod.rs, tests/integration/src/compiler_test.rs, tests/integration/src/rust_masm_tests/apps.rs
#363 
This PR adds:
- Declare the module's functions before the first function's body translation;
- Add the defined function to the module's symbol table;
- Lookup the function in the module's symbol table when translating a function call.
=> [1/x] frontend: Local function calls translation

hir2/src/dialects/builtin/ops/component.rs, hir2/src/dialects/builtin/ops/module.rs, hir2/src/ir/traits.rs
**This PR is stacked on the #381 and should be merged after it**
=> [2/x] fix: handle empty regions in `NoRegionArguments` verification

dialects/hir/src/ops/cast.rs, dialects/hir/src/ops/primop.rs, dialects/hir/src/ops/unary.rs, frontend-wasm2/src/code_translator/mod.rs, frontend-wasm2/src/code_translator/tests.rs, hir-macros/src/operation.rs, hir2/src/dialects/builtin/ops/global_variable.rs
=> [1/x] fix: restore op type constraint verification, fix `zext` vs `sext` usage in the frontend

frontend-wasm2/src/module/build_ir.rs, hir2/src/dialects/builtin/ops/segment.rs, tests/integration/expected/types/array.hir, tests/integration/src/rust_masm_tests/types.rs
#363 
**This PR is stacked on #386 and should be merged after it**
This PR adds the Wasm data segment translation. See the `test_array` test for an example.
=> [2/x] frontend: translate Wasm data segments

dialects/hir/src/builders/function.rs, frontend-wasm2/src/code_translator/mod.rs, tests/integration/expected/types/enum.hir, tests/integration/src/rust_masm_tests/types.rs
#363 
**This PR is stacked on the #387 and should be merged after it**
This PR adds translation for the `br_table` Wasm op. See `test_enum` test for the example.
=> [3/x] frontend: translate `BrTable` Wasm op

Cargo.lock, docs/usage/cargo-miden.md, docs/usage/midenc.md, midenc-driver/src/midenc.rs, tests/integration/src/rust_masm_tests/rust_sdk.rs, tools/cargo-miden/Cargo.toml, tools/cargo-miden/src/commands/new_project.rs, tools/cargo-miden/src/compile_masm.rs, tools/cargo-miden/src/lib.rs, tools/cargo-miden/tests/build.rs
Close #371 
This PR adds the `--program` flag and makes it the default for `cargo miden new` command. The entrypoint function name is hard-coded and is `entrypoint` which is highlighted in its comments in the project template.
The Miden VM new project template is added in https://github.com/0xPolygonMiden/rust-templates/pull/8 , tagged with `v0.6.0` which is used in this PR.
Besides, `--program` the `--account` and `--note` flags are also added, but made hidden until their implementation is restored after the new IR migration.
=> Add `--program` flag for `cargo miden new` command and make it the default for new projects

frontend-wasm2/src/miden_abi/mod.rs, frontend-wasm2/src/module/build_ir.rs, frontend-wasm2/src/module/module_translation_state.rs, hir2/src/dialects/builtin/builders/component.rs, hir2/src/ir/symbols/table.rs, tests/integration/expected/mem_intrinsics_heap_base.hir, tests/integration/expected/mem_intrinsics_heap_base.wat, tests/integration/src/compiler_test.rs, tests/integration/src/rust_masm_tests/apps.rs
Close #396 
This PR add translation for `mem::intrinsics::heap_base` by creating a module(`mem::intrinsics`) with an "empty" function (`heap_base`) since the real function implementation is linked at the codegen.
=> frontend: translate `mem::intrinsics::heap_base`

frontend-wasm2/src/code_translator/mod.rs, frontend-wasm2/src/intrinsics/felt.rs, frontend-wasm2/src/intrinsics/mem.rs, frontend-wasm2/src/intrinsics/mod.rs, frontend-wasm2/src/module/module_translation_state.rs, hir2/src/dialects/builtin/builders/component.rs, hir2/src/dialects/builtin/ops/module.rs, tests/integration/expected/felt_intrinsics.hir, tests/integration/expected/felt_intrinsics.wat, tests/integration/src/rust_masm_tests/apps.rs, tools/cargo-miden/src/commands/new_project.rs
#363 
This PR implements felt intrinsics translation and switch `cargo miden new` to v0.7.0 tag with program template using Felts instead of u32 (added in https://github.com/0xPolygonMiden/rust-templates/pull/9)
=> [1/x] feature(frontend): implement felt intrinsics

frontend-wasm2/src/code_translator/mod.rs, frontend-wasm2/src/code_translator/tests.rs, frontend-wasm2/src/module/build_ir.rs, frontend-wasm2/src/module/mod.rs
#363 
**This PR is stacked on the #398 and should be merged after it.**
This PR adds translation for the Wasm `if-else` op and concludes the implementation of all the missing Wasm ops that were implemented in the old frontend(IR).
=> [2/x] feature(frontend): translate Wasm `if-else` op

dialects/hir/src/builders/function.rs, frontend-wasm2/src/code_translator/mod.rs, frontend-wasm2/src/code_translator/tests.rs, hir-macros/src/operation.rs, hir2/src/dialects/builtin/builders/module.rs, hir2/src/dialects/builtin/ops/global_variable.rs, hir2/src/ir/operation.rs
#363 
It turned out that I missed `global.set` and `get` Wasm ops last time. This PR implements them and adds a frontend test `code_translator::tests::globals`
=> fix(frontend): implement Wasm `global.get` and `set` translation

examples/collatz/src/lib.rs, examples/fibonacci/src/lib.rs, tools/cargo-miden/src/commands/new_project.rs
**This PR is stacked on the #407 and should be merged after it**
Corresponding PR - https://github.com/0xPolygonMiden/rust-templates/pull/10
=> [2/x] chore: update `cargo miden new` to use `v0.8.0` of the program template

frontend-wasm2/src/miden_abi/transform.rs, frontend-wasm2/src/module/module_translation_state.rs, tests/integration/expected/abi_transform_stdlib_blake3_hash.hir, tests/integration/expected/abi_transform_tx_kernel_get_id.hir, tests/integration/expected/abi_transform_tx_kernel_get_id.wat, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.hir, tests/integration/src/rust_masm_tests/abi_transform/stdlib.rs, tests/integration/src/rust_masm_tests/abi_transform/tx_kernel.rs, tests/integration/src/rust_masm_tests/rust_sdk.rs
#363 
This PR:
- Adds synthetic function generation with Miden ABI transformation for all known transformation strategies for Miden stdlib and tx_kernel;
- Partially restores the `get_inputs` and `blake3` tests (up to HIR2 generation);
- Adds `get_id` test for testing the HIR2 generation to test the `no_transform` strategy;
**NOTE**: I think that imported functions (the ones called from the synthetic ones) should probably be defined in the separate `Component` but since it requires establishing the `World` op it deserves a separate PR. I temporarily put them in the separate module in the same component.
**EDIT**: I'm not entirely happy with the code and overall design, but I decided to leave it as is and to get back to it after the Component Model translation is implemented, since it …
=> [1/x] feature(frontend): generate synthetic functions with Miden ABI transformation (stdlib, tx_kernel);

examples/collatz/README.md
Fixing the reference to "fibonacci" in the collatz example readme
=> fix: collatz example readme

Cargo.lock, tests/integration/expected/rust_sdk/cross_ctx_account.wat, tools/cargo-miden/Cargo.toml
Close #116 
**This PR is stacked on the #417 and should be merged after it**
=> chore: switch to the published version `v0.21` of the `cargo-component` with type remapping in `wit-bindgen`

Makefile.toml, frontend-wasm2/Cargo.toml, midenc-compile/Cargo.toml, midenc-compile/src/stages/parse.rs
This fixes the issue `cargo make build` failing, and a couple related fixes found in the process.
=> fix: missing wasmparser feature causing cargo build failure

codegen/masm/intrinsics/mem.masm, codegen/masm/src/artifact.rs, codegen/masm/src/emit/mem.rs, codegen/masm/src/lib.rs, codegen/masm/src/lower/component.rs, frontend/wasm/src/component/translator.rs, frontend/wasm/src/module/module_translation_state.rs, hir/src/dialects/builtin/ops/component/interface.rs, midenc-session/src/lib.rs, tests/integration/expected/rust_sdk/cross_ctx_account.masm, tests/integration/expected/rust_sdk/cross_ctx_note.hir, tests/integration/expected/rust_sdk/cross_ctx_note.masm, tests/integration/expected/rust_sdk/cross_ctx_note.wat, tests/integration/expected/types/static_mut.masm, tests/integration/src/rust_masm_tests/rust_sdk.rs, tests/integration/src/testing/setup.rs
=> fix: note script compilation

dialects/hir/src/transforms/spill.rs, dialects/scf/src/transforms/cfg_to_scf.rs, hir-transform/src/canonicalization.rs, hir-transform/src/sccp.rs, hir-transform/src/sink.rs, hir-transform/src/spill.rs, hir/src/ir/print.rs, hir/src/pass.rs, hir/src/pass/instrumentation.rs, hir/src/pass/manager.rs, hir/src/pass/pass.rs, midenc-compile/src/compiler.rs, midenc-compile/src/stages/rewrite.rs, midenc-session/src/options/mod.rs
This PR implements the IR printing functionality, which can enabled via the use of flags passed to the compiler. The flags it introduces are:
`-Z print-ir-after-all`, `-Z print-ir-after-pass` and `-Z print-ir-after-modified`.
- `print-ir-after-all`: This enables IR printing for every pass.
- `print-ir-after-pass`: This enables IR printing for a selected number passes.
- Those passes have to be passed as a comma separated string after an equal sign, like so:
- `-Z print-ir-after-pass=canonicalizer,lift-control-flow`
- `print-if-after-modified`: This will only allow a pass to print the IR *if* it modifies the IR it received as input.
Here's an example output of the usage of these flags, these CLI examples are using the `fib.rs` available in the [Miden …
=> Add IR printing functionality to the PassManager

.github/workflows/release.yml
Hi devs!
Switch workflow to the new official repo (`release-plz/action`).
Upstream moved from `MarcoIeni/release-plz-action`; the old path is now
archived and will no longer receive updates or security fixes.
Thanks.
[Reference](https://github.com/release-plz/release-plz/pull/1849)
=> ci: switch release-plz action to new repo

Makefile.toml
This fixes an issue with `cargo make install-midenc`, as well as implements `cargo make install-cargo-miden`.
=> fix: install tasks for cargo-miden, midenc

Cargo.lock, dialects/scf/Cargo.toml, dialects/scf/src/transforms/cfg_to_scf.rs, dialects/scf/src/transforms/expected/cfg_to_scf_lift_conditional_early_exit_after.hir, dialects/scf/src/transforms/expected/cfg_to_scf_lift_conditional_early_exit_before.hir, hir-transform/src/cfg_to_scf/edges.rs, hir-transform/src/cfg_to_scf/transform.rs
This fixes the issue reported in #510, adds a new test case that covers the structure of the IR that triggered it, and adds some additional instrumentation I found helpful when diagnosing it.
=> fix(cfg-to-scf): incorrect folding of continuation region blocks

tests/integration/src/rust_masm_tests/rust_sdk.rs
Following https://github.com/0xMiden/compiler/pull/522#issuecomment-2903478063
To avoid account Wasm binary overwrite when they run in parallel. The odds of this happening were increased by setting one cargo target folder in `Makefile.toml`.
This is a quick fix, and we need to figure out a way to use isolated target folders in each test.
=> test: merge `rust_sdk_cross_ctx_account` and `rust_sdk_cross_ctx_note` tests

codegen/masm/src/lower/utils.rs, dialects/scf/src/transforms/cfg_to_scf.rs, eval/src/tests.rs, frontend/wasm/src/component/lift_exports.rs, frontend/wasm/src/component/lower_imports.rs, frontend/wasm/src/miden_abi/mod.rs, frontend/wasm/src/module/build_ir.rs, frontend/wasm/src/module/func_translator.rs, frontend/wasm/src/module/function_builder_ext.rs, hir/src/dialects/builtin/builders/function.rs, hir/src/matchers/matcher.rs, hir/src/patterns/pattern.rs, tests/integration/src/testing/setup.rs
The FunctionBuilder was requiring us to hold a mutable reference to the underlying Function, which meant that if we wished to print the current Function while tracing is enabled in the compiler, it would always fail when a FunctionBuilder is in scope.
This change refactors it to take a FunctionRef instead, and dynamically borrow as needed to avoid holding a borrow for the entire lifetime of the FunctionBuilder.
=> refactor: simplify function builder to enable better instrumentation

Cargo.lock, Cargo.toml, examples/counter-contract/Cargo.lock, examples/counter-note/Cargo.lock, examples/storage-example/Cargo.lock, hir-symbol/Cargo.toml, hir-type/Cargo.toml, hir/Cargo.toml, midenc-debug/Cargo.toml, sdk/base-macros/CHANGELOG.md, sdk/base-macros/Cargo.toml, sdk/base-macros/src/account_component_metadata.rs, sdk/base-sys/Cargo.toml, sdk/base/CHANGELOG.md, sdk/base/Cargo.toml, sdk/sdk/Cargo.toml, tests/integration/Cargo.toml, tests/rust-apps-wasm/rust-sdk/account-test/Cargo.lock, tests/rust-apps-wasm/rust-sdk/add/Cargo.lock, tests/rust-apps-wasm/rust-sdk/basic-wallet/Cargo.lock, tests/rust-apps-wasm/rust-sdk/cross-ctx-account/Cargo.lock, tests/rust-apps-wasm/rust-sdk/cross-ctx-note/Cargo.lock, tests/rust-apps-wasm/rust-sdk/p2id-note/Cargo.lock, tools/cargo-miden/Cargo.toml
This PR kicks off the release for 0.1.0, and includes updates of our dependencies, as well as a fix for the hashbrown 0.14.5/15+ upgrade issue.
@greenhat The `release-plz update` command did not work for some reason, initially I thought it was due to running `release-plz set-version` on each of the crates, but even after rolling those changes back it still failed due to an issue with resolving certain package versions when computing the diff between package versions. The crate it kept failing on was `miden-base-macros`, but I think that's a red herring, and the issue might instead be due to the fact that we are setting the crate versions to the workspace version, and `release-plz update` bumps the workspace version, which causes things to get a bit wonky. In any case, figured I'd give you …
=> release: 0.1.0

.github/workflows/ci.yml
Close #490 
The reason our cache was 4 GB is that we put cached both debug and release artifacts together. This PR splits both CI jobs and rust-caches into debug (`shared-tests`) and release (`shared-release-checks`)
=> chore: split release checks CI job and make their own rust-cache; reset prefix key

Cargo.lock, Cargo.toml, Makefile.toml, tests/integration/Cargo.toml, tests/integration/src/compiler_test.rs, tests/integration/src/rust_masm_tests/rust_sdk.rs, tests/integration/src/testing/mod.rs, tests/integration/src/testing/testnet.rs, tools/cargo-miden/src/outputs.rs
This PR takes the integration test I sketched out in Mexico that ran against the testnet, and refactors it into two parts: a generic, builder pattern-style harness/infrastructure for creating tests of this type; and a test that demonstrates its usage.
The example test from which this derived, creates an account (from our `counter-contract` example), and then creates a transaction that executes a note (from our `counter-note` example) against that account.
I have not evaluated whether the test succeeds currently, and the example test is disabled for this reason. I think some further refinement is needed to the test itself to ensure that it can be run on a repeatable basis. On a related note, I think we should set some kind of tag for these sorts of tests, so that they are only run …
=> wip: sketch out generic testnet integration test harness

Cargo.toml
Issue raised in this conversation: https://github.com/0xMiden/midenup/pull/5#discussion_r2141001835
=> chore: remove lto = "thin" from release profile

codegen/masm/src/emit/int32.rs, tests/integration/expected/examples/basic_wallet.masm, tests/integration/expected/examples/counter.masm, tests/integration/expected/examples/counter_note.masm, tests/integration/expected/examples/p2id.masm, tests/integration/expected/examples/storage_example.masm, tests/integration/expected/rust_sdk/cross_ctx_account.masm, tests/integration/expected/rust_sdk/cross_ctx_account_word_arg.masm, tests/integration/expected/rust_sdk/cross_ctx_note.masm, tests/integration/expected/rust_sdk/cross_ctx_note_word_arg.masm, tests/integration/expected/types/static_mut.masm, tests/integration/src/codegen/intrinsics/mem.rs
Close #268 
Discovered while working on #533.
This PR fixes the mask in the `trunc_int32` function and adds loading tests for `bool`, `u8` and `u16` values.
=> Fix mask in `trunc_int32` and add memory intrinsics tests for `bool`, `u8`, `u16` values

sdk/alloc/src/lib.rs, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.hir, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.masm, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.wat, tests/integration/expected/examples/p2id.hir, tests/integration/expected/examples/p2id.masm, tests/integration/expected/examples/p2id.wat, tests/integration/expected/mem_intrinsics_heap_base.hir, tests/integration/expected/mem_intrinsics_heap_base.wat
=> fix: `BumpAlloc` to make all allocations minimally VM word-aligned (16 bytes)

tools/expect-test/Cargo.toml
Fixing the error https://github.com/0xMiden/compiler/actions/runs/15998674964/job/45127945249 from the previous publishing.
=> chore: disable publishing for `midenc-expect-test` crate

tools/expect-test/Cargo.toml
Reverts https://github.com/0xMiden/compiler/pull/580
We need to publish `midenc-expect-test` crate.
=> chore: remove `publish = false` for `midenc-expect-test` crate

docs/src/usage/cargo-miden.md, tools/cargo-miden/src/commands/example_project.rs, tools/cargo-miden/src/commands/mod.rs, tools/cargo-miden/src/commands/new_project.rs, tools/cargo-miden/src/lib.rs, tools/cargo-miden/tests/build.rs
Close #514 
**This PR is stacked on the #588 and should be merged after it**
Counter PR in `rust-templates` repo - https://github.com/0xMiden/rust-templates/pull/17
This PR:
- Changes the new project template for account and note script to be clean `add` example (like the Rust `cargo new` for a library);
- Adds `cargo miden example` command that copies an example from the `examples` folder of the compiler repo;
=> feature: add `cargo miden example`, clean up `new` project templates

Cargo.lock, dialects/scf/Cargo.toml, dialects/scf/src/canonicalization.rs, dialects/scf/src/canonicalization/expected/fold_redundant_yields_all_but_one_switch_after.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_all_but_one_switch_before.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_all_if_switch_after.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_all_if_switch_before.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_all_switch_if_after.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_all_switch_if_before.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_different_pos_switch_after.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_different_pos_switch_before.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_effects_if_after.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_effects_if_before.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_many_switch_after.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_many_switch_before.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_subset_if_switch_after.hir, dialects/scf/src/canonicalization/expected/fold_redundant_yields_subset_if_switch_before.hir, dialects/scf/src/canonicalization/fold_redundant_yields.rs, dialects/scf/src/ops.rs, hir/src/dialects.rs, hir/src/dialects/test.rs, hir/src/dialects/test/builders.rs, hir/src/dialects/test/ops/binary.rs
At this stage this is only `scf.if` and `scf.index_switch`.  It will try to replace the entire operation if all yields within are of the same values, or it will cull those yields down to only those which differ per region.
Something similar could be applied to `scf.while` but while I tried to get it going, it was both more complicated and felt like it was addressing a corner case.  Finding redundant values between the 'before' and 'after' blocks might be worthwhile, though it would be unlikely the compiler would generate such values.  And then lifting out redundant yields (of values which dominate the `while`) could also be done.
To test the output I've created a pass which runs a single rewriter.  It's handy to use a pass manager to run it because a) the `LiftControlFlowToSCF` transform …
=> Add a rewriter pass for folding redundant yields from SCF control flow.

codegen/masm/src/lower/lowering.rs
While looking at our lowering for `hir.ptr_to_int`, I realized that we weren't correctly renaming the result value on the operand stack, which is pushed as a type, to an SSA value, because we were implementing the lowering manually, rather than going through `InstOpEmitter`. The effect of this is that subsequent operand stack scheduling that tried to look up that value by name, would fail to find it.
We weren't yet using `hir.ptr_to_int` anywhere, which is why this hasn't come up yet.
=> fix(codegen): missing result renaming in ptrtoint lowering

Cargo.lock, Cargo.toml, Makefile.toml, benches/Cargo.toml, benches/README.md, benches/benches/is_prime_bench.rs, benches/src/is_prime.rs, benches/src/lib.rs
This PR adds a `benches/` directory with an extensible framework for benchmarking Miden compiler programs. The system automatically compiles Rust programs with `cargo miden build`, executes them with `midenc run`, and measures VM cycles and performance metrics.
**Usage:**
```bash
cargo run -p miden-compiler-benches --bin is_prime
cargo run -p miden-compiler-benches --bin is_prime -- --input 97 --iterations 3
```
The framework is designed to be easily extended for benchmarking other Miden programs by adding new binaries to `benches/src/`.
=> Add extensible benchmarking system with `is_prime` benchmark

hir/src/dialects/builtin/builders/component.rs, hir/src/dialects/builtin/builders/module.rs, hir/src/dialects/builtin/builders/world.rs, hir/src/ir/builder.rs, hir/src/ir/operation.rs, hir/src/ir/symbols.rs, hir/src/lib.rs, hir/src/patterns/rewriter.rs
Closes: #404
This PR implements logic to add an Operation which implements the `Symbol` trait to its parent `SymbolTable`, after the Operation is built.
This is done via the `EntityListItem::on_inserted` and `EntityListItem::on_removed` hooks, which are run after an `Operation` is added or removed removed from an `EntityList` respectively. This executed shortly after `Operation` creation, during the final stages of the `OperationBuilder::build` function.
Originally, `Operation`s were borrowed before entering this function, which caused errors when trying to add them to their parent's `SymbolTable`. To prevent this, some functions related to `Operation` insertion were moved to `OperationRef` and now avoid borrowing the underlying `Operation`.
=> Add Op registration into symbol table inside OpBuilder 

examples/basic-wallet/cargo-generate.toml, examples/collatz/cargo-generate.toml, examples/counter-contract/cargo-generate.toml, examples/counter-note/cargo-generate.toml, examples/fibonacci/cargo-generate.toml, examples/is-prime/cargo-generate.toml, examples/p2id-note/cargo-generate.toml, examples/p2id-note/src/lib.rs, examples/storage-example/cargo-generate.toml, frontend/wasm/src/miden_abi/transform.rs, frontend/wasm/src/miden_abi/tx_kernel/account.rs, sdk/base-sys/src/bindings/account.rs, sdk/base-sys/src/bindings/types.rs, sdk/base-sys/wit/miden-core-base.wit, sdk/base/wit/miden.wit, tests/integration/expected/abi_transform_tx_kernel_get_id.hir, tests/integration/expected/abi_transform_tx_kernel_get_id.wat, tests/integration/expected/examples/p2id.hir, tests/integration/expected/examples/p2id.masm, tests/integration/expected/examples/p2id.wat, tests/integration/src/rust_masm_tests/abi_transform/tx_kernel.rs, tools/cargo-miden/src/commands/example_project.rs, tools/cargo-miden/src/commands/new_project.rs, tools/cargo-miden/src/lib.rs, tools/cargo-miden/src/utils.rs, tools/cargo-miden/tests/build.rs
Close #616
This PR:
- Updates Miden SDK `AccountId` type and `account::get_id()` for two felts (prefix and suffix) account ids;
- Uses local compiler path in `ExampleCommand` under tests;
=> fix: update Miden SDK `AccountId` type and `account::get_id()` for two felts (prefix and suffix) account ids

docs/src/usage/cargo-miden.md, docs/src/usage/midenc.md, rust-toolchain.toml
Reading the [miden compiler documenation](https://0xmiden.github.io/compiler/), there is a warning message stating that the compiler uses an older rust version from the one it really uses.
This PR updates the documentation and adds a small "reminder" in `rust-toolchain.toml`.
=> docs: update toolchain version in documentations

sdk/alloc/src/lib.rs, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.hir, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.masm, tests/integration/expected/abi_transform_tx_kernel_get_inputs_4.wat, tests/integration/expected/examples/p2id.hir, tests/integration/expected/examples/p2id.masm, tests/integration/expected/examples/p2id.wat, tests/integration/expected/mem_intrinsics_heap_base.hir, tests/integration/expected/mem_intrinsics_heap_base.wat, tests/integration/expected/vec_alloc_vec.hir, tests/integration/expected/vec_alloc_vec.masm, tests/integration/expected/vec_alloc_vec.wat
The linear memory heap must not spill over into the region reserved for procedure locals, which begins at `2^30` in Miden's address space. In Rust address space it should be `2^30 * 4` but since it overflows the usize which is 32-bit on wasm32 we use `u32::MAX`. "-1" is to avoid `xor` op in the compiled Wasm.
=> fix: HEAP_END to represent the Miden limit in the Rust address space

codegen/masm/src/artifact.rs, tests/integration/src/rust_masm_tests/rust_sdk.rs
Close #637 
Pass intrinsics modules to the assembler via `Assembler::add_module`.
=> fix: remove intrinsics exports from compiled MASM library

.github/workflows/release.yml, codegen/masm/Cargo.toml, dialects/hir/Cargo.toml, dialects/scf/Cargo.toml, frontend/wasm/Cargo.toml, hir-analysis/Cargo.toml, hir/Cargo.toml, sdk/base-macros/Cargo.toml, tests/integration-node/Cargo.toml, tests/integration/Cargo.toml, tools/cargo-miden/Cargo.toml
This PR fixes:
1. Using our crates in `dev-dependencies` with only `path` specified. Fixes https://github.com/0xMiden/compiler/actions/runs/17444451785/job/49563651241 error.
Since `release-plz` does not consider dev-dependencies when computing the publish order the publishing will fail for a crate that has a not-yet-published crate version in the dev-dependencies.
2. Removes rust-cache for the `release-plz` CI job.
Apparently, `gix` fails if the registry index is present. See failed https://github.com/0xMiden/compiler/actions/runs/17444451785/job/49535289715
**After merging this PR, the CI job will publish all the unpublished crates.**
=> Fix and publish the rest of the v0.4.1 crates

examples/p2id-note/src/lib.rs, sdk/base-sys/src/bindings/types.rs, tests/integration/expected/examples/p2id.hir, tests/integration/expected/examples/p2id.masm, tests/integration/expected/examples/p2id.wat
Resolves #702 
This PR adds on two new features to the `AccountId` type:
1) Enables the `==` operator to be used with the `AccountId` type.
2) Adds a `AccountId::from` method to convert two `Felt` types into an `AccountId`.
The P2ID script is updated to use these two new features.
=> feat: enable `==` operator for `AccountId` type
